remote_theme: pages-themes/tactile
plugins:
- jekyll-remote-theme

title: ohikkoshi.github.io
description: ohikkoshi.github.io
show_downloads: false   # ["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics:       # [Your Google Analytics tracking ID]
